//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBBOERSE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JOBBOERSE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bad {
            get {
                object obj = ResourceManager.GetObject("bad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap good {
            get {
                object obj = ResourceManager.GetObject("good", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///	
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!-- Version: JB P63.0.2.501  --&gt;
        ///
        ///
        ///
        ///&lt;html lang=&quot;de&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot; /&gt;
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///	
        ///		
        ///			
        ///			
        ///
        ///			
        ///				
        ///				
        ///					
        ///					
        ///						
        ///							
        ///							
        ///								&lt;title&gt;JOBBĂ–RSE - Ergebnisse meiner Deutschlandsuche - Arbeit&lt;/title&gt;
        ///							
        ///						
        ///					
        ///				
        ///			
        ///		
        ///	
        ///	
        ///
        ///&lt;meta name=&quot;description&quot;
        ///	content=&quot;Bei Deutschlands grĂ¶Ăźtem Online-Jobportal finden Sie schnell und einfach die passende Stelle oder den passenden Bewe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///	
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!-- Version: JB P63.0.2.501  --&gt;
        ///
        ///
        ///
        ///&lt;html lang=&quot;de&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot; /&gt;
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///	
        ///		
        ///			
        ///			
        ///
        ///			
        ///				
        ///				
        ///					
        ///					
        ///						
        ///							
        ///							
        ///								&lt;title&gt;JOBBĂ–RSE - Stellenangebot - Physiotherapeut/In-Manualtherapeut/In (Physiotherapeut/in)&lt;/title&gt;
        ///							
        ///						
        ///					
        ///				
        ///			
        ///		
        ///	
        ///	
        ///
        ///&lt;meta name=&quot;description&quot;
        ///	content=&quot;Bei Deutschlands grĂ¶Ăźtem Online-Jobportal finden Sie schnell und einfach die passend [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlOffer {
            get {
                return ResourceManager.GetString("htmlOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=zugang.stellenangebotesuchen.ergebnisanzeigedersuchenachstellenangeboten.berufsbezeichnungdesstellenangebots_.
        /// </summary>
        internal static string pattern1 {
            get {
                return ResourceManager.GetString("pattern1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; href=&quot;)(.*)(?=&quot; class=&quot;internerLink).
        /// </summary>
        internal static string pattern1_1 {
            get {
                return ResourceManager.GetString("pattern1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=ruckfragenundbewerbungenan_-2147483648&quot;&gt;)(.*)(?=span&gt;).
        /// </summary>
        internal static string pattern2 {
            get {
                return ResourceManager.GetString("pattern2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=vorname_-2147483648&quot;&gt;)(.*)(?=span&gt;).
        /// </summary>
        internal static string pattern3 {
            get {
                return ResourceManager.GetString("pattern3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=nachname_-2147483648&quot;&gt;)(.*)(?=span&gt;).
        /// </summary>
        internal static string pattern4 {
            get {
                return ResourceManager.GetString("pattern4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=Strasse_-2147483648&quot;&gt;)(.*)(?=span&gt;).
        /// </summary>
        internal static string pattern5 {
            get {
                return ResourceManager.GetString("pattern5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=Plz_-2147483648&quot;&gt;)(.*)(?=span&gt;).
        /// </summary>
        internal static string pattern6 {
            get {
                return ResourceManager.GetString("pattern6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=Ort_-2147483648&quot;&gt;)(.*)(?=span&gt;).
        /// </summary>
        internal static string pattern7 {
            get {
                return ResourceManager.GetString("pattern7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;= href=&quot;mailto:)(.*)(?=&quot; class).
        /// </summary>
        internal static string pattern8 {
            get {
                return ResourceManager.GetString("pattern8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=                        )(.*)(?=).
        /// </summary>
        internal static string pattern9 {
            get {
                return ResourceManager.GetString("pattern9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=execution=e)(.*)(?=s1).
        /// </summary>
        internal static string patternSideLink1 {
            get {
                return ResourceManager.GetString("patternSideLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
